FROM node:18-bullseye

# Create app directory
WORKDIR /app

# Enable corepack and prepare pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy only package manifests to leverage docker cache
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install --frozen-lockfile --prefer-offline

# Copy rest of the project
COPY . .

EXPOSE 5170

# Start dev server
CMD ["pnpm", "dev", "-p", "5170"]
